"""
Vector + Graph Retriever Agent

This workshop demonstrates an agent with vector search that retrieves documents
and traverses the graph to find related context using the Microsoft Agent Framework
with Microsoft Foundry (V2 SDK - azure-ai-projects) and neo4j-graphrag-python.

Run with: uv run python solutions/02_02_vector_graph_agent.py
"""

import asyncio
from typing import Annotated

from neo4j_graphrag.retrievers import VectorCypherRetriever
from neo4j_graphrag.schema import get_schema
from pydantic import Field

from agent_framework.azure import AzureAIClient
from azure.identity.aio import AzureCliCredential

from config import get_neo4j_driver, get_agent_config, get_embedder

"""
This RETRIEVAL_QUERY is appended to the Cypher query automatically generated by the
neo4j-graphrag-python library's VectorCypherRetriever. The library first calls
the vector index and yields 'node' and 'score' variables, which are then used
by this query.

The conceptual flow is:
CALL db.index.vector.queryNodes($index_name, $top_k, $embedding)
YIELD node, score
// ... then this RETRIEVAL_QUERY is appended here ...

- `node`: This represents the specific Chunk node found by the vector search
  (the text segment that mathematically matches your query).
- `score`: The similarity score (0.0 to 1.0) of the vector match.
"""
# Retrieval query that enriches vector search results with company and risk context
RETRIEVAL_QUERY = """
MATCH (node)-[:FROM_DOCUMENT]-(doc:Document)-[:FILED]-(company:Company)
OPTIONAL MATCH (company)-[:FACES_RISK]->(risk:RiskFactor)
WITH node, score, company, collect(risk.name) as risks
WHERE score IS NOT NULL
RETURN
    node.text as text,
    score,
    {company: company.name, risks: risks} AS metadata
ORDER BY score DESC
"""


def create_tools(driver):
    """Create tools with the given driver."""
    embedder = get_embedder()

    vector_retriever = VectorCypherRetriever(
        driver=driver,
        index_name="chunkEmbeddings",
        embedder=embedder,
        retrieval_query=RETRIEVAL_QUERY,
    )

    def get_graph_schema() -> str:
        """Get the schema of the graph database including node labels, relationships, and properties."""
        return get_schema(driver)

    def retrieve_financial_documents(
        query: Annotated[str, Field(description="The search query to find relevant documents")]
    ) -> str:
        """Find details about companies in their financial documents using semantic search."""
        results = vector_retriever.search(query_text=query, top_k=3)
        if not results.items:
            return "No documents found matching the query."
        return "\n\n".join(item.content for item in results.items)

    return [get_graph_schema, retrieve_financial_documents]


async def run_agent(query: str):
    """Run the agent with the given query."""
    config = get_agent_config()

    with get_neo4j_driver() as driver:
        tools = create_tools(driver)

        async with AzureCliCredential() as credential:
            client = AzureAIClient(
                project_endpoint=config.project_endpoint,
                model_deployment_name=config.model_name,
                async_credential=credential,
            )

            async with client.create_agent(
                name="workshop-vector-graph-agent",
                instructions=(
                    "You are a helpful assistant that can answer questions about "
                    "a graph database containing financial documents. You can retrieve "
                    "the schema and search for relevant documents."
                ),
                tools=tools,
            ) as agent:
                print(f"User: {query}\n")
                print("Assistant: ", end="", flush=True)

                async for update in agent.run_stream(query):
                    if update.text:
                        print(update.text, end="", flush=True)

                print("\n")


if __name__ == "__main__":
    asyncio.run(run_agent("Summarise what risk factors are mentioned in Apple's financial documents?"))


# Example queries to try:
# - Summarize the schema of the graph database.
# - What are the main risk factors mentioned in the documents?
# - Tell me about cybersecurity threats in financial services
# - What products does Microsoft mention in its financial documents?
# - How are companies connected through their mentioned products?
# - What type of questions can I ask about Apple using the graph database?
